from pyforth.core import WORD, XT

from . import (
    arithmetic,
    branching,
    comments,
    comparison,
    doloop,
    heap,
    logical,
    loops,
    output,
    primitives,
    stacks,
    fixed_point,
    strings,
)


dictionary: dict[WORD, XT] = {
    "\\": comments.xt_c_eol_comment,
    "(": comments.xt_c_definition_comment,
    ":": primitives.xt_c_colon,
    ";": primitives.xt_c_semi,
    "'": primitives.xt_r_tick,
    "execute": primitives.xt_r_execute,
    '[compile]': primitives.xt_c_bracket_compile,
    "postpone": primitives.xt_c_postpone,
    "immediate": primitives.xt_r_immediate,
    "recurse": primitives.xt_c_recurse,
    "if": branching.xt_c_if,
    "else": branching.xt_c_else,
    "then": branching.xt_c_then,
    "begin": loops.xt_c_begin,
    'again': loops.xt_c_again,
    "until": loops.xt_c_until,
    "while": loops.xt_c_while,
    "repeat": loops.xt_c_repeat,
    "do": doloop.xt_c_do,
    "loop": doloop.xt_c_loop,
    'exit': primitives.xt_c_exit,
    'i': doloop.loop_index_factory(1, 'i'),
    'j': doloop.loop_index_factory(2, 'j'),
    'k': doloop.loop_index_factory(3, 'k'),
    "+": arithmetic.xt_r_add,
    "-": arithmetic.xt_r_sub,
    "/": arithmetic.xt_r_div,
    'mod': arithmetic.xt_r_mod,
    "*": arithmetic.xt_r_mul,
    'depth': stacks.xt_r_depth,
    "drop": stacks.xt_r_drop,
    "pick": stacks.xt_r_pick,
    "swap": stacks.xt_r_swap,
    'emit': output.xt_r_emit,
    ".": output.xt_r_dot,
    "dump": output.xt_r_dump,
    "=": comparison.xt_r_eq,
    ">": comparison.xt_r_gt,
    "<": comparison.xt_r_lt,
    "lshift": arithmetic.xt_r_lshift,
    "rshift": arithmetic.xt_r_rshift,
    'and': logical.xt_r_and,
    'or': logical.xt_r_or,
    'invert': logical.xt_r_invert,
    'xor': logical.xt_r_xor,
    ",": heap.xt_r_coma,
    "@": heap.xt_r_at,
    "!": heap.xt_r_bang,
    ">r": stacks.xt_r_to_rs,
    "r>": stacks.xt_r_from_rs,
    "r@": stacks.xt_r_rs_at,
    "allot": heap.xt_r_allot,
    "create": primitives.xt_r_create,
    "does>": primitives.xt_r_does,
    'here': heap.xt_r_here,
    'precision': fixed_point.xt_r_get_precision,
    'set-precision': fixed_point.xt_r_set_precision,
    "f.": fixed_point.xt_r_dot_f,
    "f+": arithmetic.xt_r_add,
    "f-": arithmetic.xt_r_sub,
    "f*": fixed_point.xt_r_f_mul,
    'f/': fixed_point.xt_r_f_div,
    'f**': fixed_point.xt_r_f_power,
    "fsqrt": fixed_point.xt_r_f_sqrt,
    "fexp": fixed_point.xt_r_f_exp,
    "fln": fixed_point.xt_r_f_ln,
    "flog": fixed_point.xt_r_f_log,
    "fsin": fixed_point.xt_r_f_sin,
    "fcos": fixed_point.xt_r_f_cos,
    "ftan": fixed_point.xt_r_f_tan,
    "fatan2": fixed_point.xt_r_f_atan2,
    "facos": fixed_point.xt_r_f_acos,
    "fasin": fixed_point.xt_r_f_asin,
    "fatan": fixed_point.xt_r_f_atan,
    "fcosh": fixed_point.xt_r_f_cosh,
    "fsinh": fixed_point.xt_r_f_sinh,
    "ftanh": fixed_point.xt_r_f_tanh,
    ".\"": strings.xt_c_dot_quote,
    "s\"": strings.xt_c_s_quote,
    "char": strings.xt_r_char,
    "[char]": strings.xt_c_bracket_char,
    'c"': strings.xt_c_char_quote,
    'count': strings.xt_r_count,
    "type": strings.xt_r_type,
}
